# Generated by Django 3.2.25 on 2025-01-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(blank=True, max_length=255, null=True)),
                ('coupon_name', models.CharField(blank=True, max_length=255, null=True)),
                ('coupon_type', models.CharField(blank=True, max_length=255, null=True)),
                ('coupon_category', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('image_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='productmaster',
            old_name='name',
            new_name='product_name',
        ),
    ]
