# Generated by Django 3.2.25 on 2025-01-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20250122_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='product_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
