# Generated by Django 3.2.25 on 2025-01-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productmaster_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmaster',
            name='coupon_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
