# Generated by Django 3.2.25 on 2025-01-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_couponmaster_coupon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmaster',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
